<Project>
 <ItemGroup><ProjectReference Include="$(MSBuildThisFileDirectory)NoteTaker.SpeechWorker/NoteTaker.SpeechWorker.csproj" ReferenceOutputAssembly="false" /></ItemGroup>
 <Target Name="CopySpeechWorker" AfterTargets="Build">
  <ItemGroup><SpeechWorkerFiles Include="$(MSBuildThisFileDirectory)NoteTaker.SpeechWorker/bin/$(Configuration)/$(TargetFramework)/$(RuntimeIdentifier)/**/*" /></ItemGroup>
  <Copy SourceFiles="@(SpeechWorkerFiles)" DestinationFiles="@(SpeechWorkerFiles->'$(OutDir)SpeechWorker/%(RecursiveDir)%(Filename)%(Extension)')" SkipUnchangedFiles="true" />
 </Target>
 <Target Name="PublishSpeechWorker" AfterTargets="Publish">
  <MSBuild Projects="$(MSBuildThisFileDirectory)NoteTaker.SpeechWorker/NoteTaker.SpeechWorker.csproj" Targets="Publish" Properties="Configuration=$(Configuration);RuntimeIdentifier=$(RuntimeIdentifier);SelfContained=$(SelfContained);PublishDir=$([System.IO.Path]::GetFullPath('$(PublishDir)'))SpeechWorker/" />
 </Target>
</Project>
